name: Merge subtitles

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

permissions:
  contents: write

env:
  show: Bakemonogatari

jobs:
  merge:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        episodes: [01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12 ,13, 14, 15]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle
    - name: Merge subtitle
      run: ./gradlew merge.${{matrix.episodes}}
    # - name: Move merged subtitle
    #   run: mv "${{matrix.episodes}}/Bake${{matrix.episodes}} - Merged.ass" "fonts/"
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Bake${{matrix.episodes}} 
        path: ${{matrix.episodes}}/Bake${{matrix.episodes}} - Merged.ass
